# Base n8n
FROM n8nio/n8n:1.110.1

# Variáveis do Postgres
ARG PGPASSWORD PGHOST PGPORT PGDATABASE PGUSER
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

# Variáveis do Redis
ARG REDISHOST REDISPORT REDISUSER REDISPASSWORD
ENV QUEUE_BULL_REDIS_HOST=$REDISHOST
ENV QUEUE_BULL_REDIS_PORT=$REDISPORT
ENV QUEUE_BULL_REDIS_USERNAME=$REDISUSER
ENV QUEUE_BULL_REDIS_PASSWORD=$REDISPASSWORD
ENV QUEUE_BULL_REDIS_DB=0

# Configuração do Worker
ENV EXECUTIONS_MODE=queue
ENV OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV GENERIC_TIMEZONE=America/Sao_Paulo
ENV N8N_LOG_LEVEL=debug

# Inicialização do Worker
CMD ["n8n", "worker"]
