FROM n8nio/n8n:1.123.11

# Configuração do Worker
ENV EXECUTIONS_MODE=queue
ENV OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV GENERIC_TIMEZONE=America/Sao_Paulo
ENV N8N_LOG_LEVEL=debug

# Inicialização do Worker
CMD ["n8n", "worker"]
